### ISSUE TITLE
HTTP proxy setup is handled incorrectly

### ISSUE THREAD

**Issue by viz-prakash** [lagranges/people_also_ask#22]
At this [line](https://github.com/lagranges/people_also_ask/blob/d54aa0cd8d7e85a969829a1ce217cc5afdb7f6e9/people_also_ask/request/session.py#L57C18-L57C18) when setting up the HTTP proxy the statement `proxy = f"http://{proxy}"` causes an error because if I pass proxy as 'http://my_IP:port' it will change it to `'http://http://my_IP:port'`.

Instead, just return dict of 'http' as `{'http': proxy}`.

I have tested this change and it works.

**Comment by lagranges** [comment]
Hey viz-parkash, tks for raising.  It should be fixed now.

**Comment by viz-prakash** [comment]
@lagranges Thanks a bunch!
