### ISSUE TITLE
error in extracting questions

### ISSUE THREAD

**Issue by mmm88819** [lagranges/people_also_ask#3]
Instead of only getting the question, it also gets the Search for: text. 
![image](https://user-images.githubusercontent.com/16883988/130482470-74fce6ee-bf7a-41e7-afd6-cb8a524af510.png)
getting this question with this library would result in this string: 
'Can I test myself for diabetes?Search for:Can I test myself for diabetes?'
instead of just:
'Can I test myself for diabetes?'

**Comment by lagranges** [comment]
Hi @mmm88819 

This issue should be fixed in the latest version.

Best regards,

Tuan
