### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by axelabbas** [lagranges/people_also_ask#4]
`Traceback (most recent call last):
  File filename, line 3, in <module>
    people_also_ask.get_simple_answer("why is air blank")
  File Python\Python310\lib\site-packages\people_also_ask\google.py", line 163, in get_simple_answer
    document = search(question)
  File Python\Python310\lib\site-packages\people_also_ask\tools.py", line 29, in wrapper
    return func(*args, **kwargs)
  File Python\Python310\lib\site-packages\people_also_ask\google.py", line 50, in search
    raise GoogleSearchRequestFailedError(URL, keyword)
people_also_ask.exceptions.GoogleSearchRequestFailedError: ('https://www.google.com/search', 'why is air blank')`

freshly installed the package on windows 10, python 3.10, using pip install people_also_ask

**Comment by liang-cicada** [comment]
Same issue

**Comment by lagranges** [comment]
Same issue #8
