### ISSUE TITLE
Generate_Answer issue

### ISSUE THREAD

**Issue by sj7272** [lagranges/people_also_ask#5]
Hi,
Python noob, but after every other example works as shown, the generate_answer function isn't giving me what I expected.
I'm not even sure this is an error or just that I need further processing.
Any advice?

`people_also_ask.generate_answer("Dog Breeds")`

returns..
<generator object generate_answer at 0x7f9e81b2a660>

**Comment by otherland** [comment]
Generator functions are a special kind of function that return a [lazy iterator](https://en.wikipedia.org/wiki/Lazy_evaluation). These are objects that you can loop over like a [list](https://realpython.com/python-lists-tuples/). However, unlike lists, lazy iterators do not store their contents in memory.

You would need to iterate over the generator object to yield its elements.

```
for answer in people_also_ask.generate_answer("Dog Breeds"):`
    print(answer)

```
