### ISSUE TITLE
How to use proxies with people also ask?

### ISSUE THREAD

**Issue by pantdeepakk5** [lagranges/people_also_ask#9]
I am currently working on a large scale project. 

With such volume
I want to take proxy approach to avoid google ban. 

But there are no option to include them. 

Any help or guide?
Thanks

**Comment by lagranges** [comment]
Hi @pantdeepakk5 

Yes, proxy will be available very soon.

**Comment by pushkarsingh32** [comment]
Okay Waiting... 
Thanks

**Comment by grydev** [comment]
> Hi @pantdeepakk5
> 
> Yes, proxy will be available very soon.

Sorry to ask, but do you know when the proxy feature will be available?

**Comment by lagranges** [comment]
Hello,

Proxies is available in the  latest version (1.1.0)
here is an example
https://github.com/lagranges/people_also_ask#using-proxies

**Comment by lanka649** [comment]
> I am currently working on a large scale project.
> 
> With such volume I want to take proxy approach to avoid google ban.
> 
> But there are no option to include them.
> 
> Any help or guide? Thanks

Hello @pantdeepakk5, are you able to use the latest code with proxies?

**Comment by lagranges** [comment]
Hello, I've noticed some other feedback regarding the proxy, so I assume it's working now. I'll close this issue, but feel free to open a new one if you encounter any further difficulties.
